name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    
    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Set up Android Emulator
      uses: reactivecircus/android-emulator-runner@v3
      with:
        api-level: 34
        target: google_apis
        arch: x86_64
        profile: Pixel_6
        script: echo "Emulator is ready"
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew build --stacktrace --info
    
    - name: Run Unit Tests
      run: ./gradlew test --stacktrace --info
    
    - name: Run UI Tests
      run: ./gradlew connectedAndroidTest --stacktrace --info 
